server:
  port: 3001

spring:
  datasource-gdb:
    jdbc-url: jdbc:agensgraph://220.76.92.129:15432/infocz
    driverClassName: net.bitnine.agensgraph.Driver
    username: infocz
    password: "dlsvhTlwm4ever"
    database: infocz
    # jdbc-url: jdbc:agensgraph://192.168.0.65:25431/ldbc
    # username: agens
    # password: "agens"
    # database: ldbc

    mapper-locations: "classpath:/mapper/gdb/**/*.xml"
    mybatis-config: "classpath:/config/mybatis-config.xml"
    hikari:
      maximum-pool-size: 24
      connection-test-query: "SELECT NOW() FROM dual;"

  datasource-rdb:
    jdbc-url: jdbc:mariadb://220.76.92.129:3001/sample
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: "!@Rjwu34"
    mapper-locations: "classpath:/mapper/rdb/**/*.xml"
    mybatis-config: "classpath:/config/mybatis-config.xml"
    hikari:
      maximum-pool-size: 24
      connection-test-query: "SELECT NOW() FROM dual:"

  datasource-rdb2:
    jdbc-url: jdbc:mariadb://220.76.92.129:3001/sample
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: "!@Rjwu34"
    mapper-locations: "classpath:/mapper/rdb2/**/*.xml"
    mybatis-config: "classpath:/config/mybatis-config.xml"
    hikari:
      maximum-pool-size: 24
      connection-test-query: "SELECT NOW() FROM dual:"

jwt:
  header: Authorization
  secret: and0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdp
  token-validity-in-seconds: 3600

logging:
  level:
    root: info
    com: 
      infocz: 
        infoCruise:
          api: debug
            