server:
  port: 8022

spring:
  datasource:
    jdbc-url: jdbc:agensgraph://220.76.92.129:15432/infocz
    driverClassName: net.bitnine.agensgraph.Driver
    username: infocz
    password: "dlsvhTlwm4ever"
    mapper-locations: "classpath:/mapper/**/*.xml"
    hikari:
      maximum-pool-size: 24
      connection-test-query: "SELECT NOW() FROM dual:"

logging:
  level:
    root: info
    com: 
      infocz: 
        igviewer:
          api: debug
            